### ISSUE TITLE
Step 11 does not work for me

### ISSUE THREAD

**Issue by DtXFS** [Nkap23/TensorFlow_with_Colab_tutorial#1]
Hello,
I am following your tutorial and so far everything worked out fine for me, because it is perfectly described. But with Step 11 I get a lot of traceback warnings and the two .record-files are not generated. I checked if all the paths are right, and if the generate_tfrecord.py and the label_map.pbtxt are in place. 
Can you somehow help me?

Here is a part of the feedback I get while running Step 11:
/content/gdrive/My Drive/TensorFlow/scripts/preprocessing
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/utils/label_map_util.py", line 159, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 734, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 802, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 827, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 849, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 1048, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)

Thanks in advance!

**Comment by Nkap23** [comment]
Hi!
Have you added the correct paths to the train/test folder and the annotations folder in step 11?

Also, make sure that the labels you have used to annotate your image and the 'name' you have used in label_map.pbtxt are exactly the same! 
(like if the label in the image is 'banana' and if you have used 'Banana' in label_map, the code will throw an error)

Also, is this the whole feedback you are getting after running? Generally, the last few lines should describe the error you are getting! 

Also a NOTE:
If you are working over multiple sessions, you need to run steps 6 to steps 9 every new session!

**Comment by DtXFS** [comment]
In Step 15 do I have to put in the Path of the pre-trained-model or the empty model folder? Because just the name of the downloaded model is not identical it is "my_ssd_resnet50_v1_fpn" in the new folder and "ssd_resnet50_v1_fpn_640x640_coco17_tpu-8" in the downloadad folder...
!python model_main_tf2.py --model_dir=**models/my_ssd_resnet50_v1_fpn** --pipeline_config_path=models/**my_ssd_resnet50_v1_fpn/pipeline.config**#
 !python model_main_tf2.py --model_dir=models/[name_of_pre-trained-model_you_downloaded] --pipeline_config_path=models/[name_of_pre-trained-model_you_downloaded]/pipeline.config

**Comment by Nkap23** [comment]
For Tensorboard, you should have a setting option on the top-right corner of the Tensorboard display. 
Go to that settings and check the 'reload data' box. This will reload the TensorFlow automatically. You can also set the reload period (if the reload period is 30, the Tensorboard will reload every 30 secs automatically)

For step 15 error, try reducing the batch size in pipeline.config and restarting the session!
You have to put the path of the new empty model folder which contains the modified pipeline.config file  (models/my_ssd_resnet50_v1_fpn)

**Comment by Nkap23** [comment]
Closing this due to lack of activity!
