### ISSUE TITLE
Hi i am using Google Colab and i stuck at n10, the error is below

### ISSUE THREAD

**Issue by nehme77** [Nkap23/TensorFlow_with_Colab_tutorial#11]
/content/gdrive/MyDrive/Colab Notebooks/VGG-ImageDetection/TensorFlow/models/research/object_detection/builders
Traceback (most recent call last):
  File "model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python3.7/dist-packages/object_detection-0.1-py3.7.egg/object_detection/builders/model_builder.py", line 55, in <module>
    from object_detection.models import center_net_resnet_v1_fpn_feature_extractor
  File "/usr/local/lib/python3.7/dist-packages/object_detection-0.1-py3.7.egg/object_detection/models/center_net_resnet_v1_fpn_feature_extractor.py", line 24, in <module>
    from object_detection.models.keras_models import resnet_v1
  File "/usr/local/lib/python3.7/dist-packages/object_detection-0.1-py3.7.egg/object_detection/models/keras_models/resnet_v1.py", line 24, in <module>
    from tensorflow.python.keras.applications import resnet
ModuleNotFoundError: No module named 'tensorflow.python.keras.applications'

**Comment by christalker-java** [comment]
Hi we have the same problem, did you fix the problem?
